[project]
name = "waveform_analysis"
version = "0.0.1"
description = "Waveform analyzer tools for the Proteus ecosystem"
dependencies = [
  "pywellen",
]

[build-system]
requires = ["uv_build >= 0.7.19, <0.9.0"]
build-backend = "uv_build"
