services:
  ecosystem:
    build:
      context: .
      args: # add more flags here to install EVAL-HD, riscv-formal, ...
        INSTALL_TOOLCHAIN: "true"
    container_name: ecosystem
    restart: "no"
    stdin_open: true
    tty: true
    working_dir: /ecosystem
    volumes:
      - ./core:/ecosystem/core
      - ./synthesis:/ecosystem/synthesis
      - ./noninterference-testing:/ecosystem/noninterference-testing
      - ./waveform-analysis:/ecosystem/waveform-analysis
      - ./install-scripts:/ecosystem/install-scripts
      - ./formal-verification:/ecosystem/formal-verification
    command: "/bin/bash"
  ecosystem-prebuilt:
    image: ghcr.io/proteus-core/ecosystem
    restart: "no"
    stdin_open: true
    tty: true
    working_dir: /ecosystem
    volumes:
      - ./core:/ecosystem/core
      - ./synthesis:/ecosystem/synthesis
      - ./noninterference-testing:/ecosystem/noninterference-testing
      - ./waveform-analysis:/ecosystem/waveform-analysis
      - ./install-scripts:/ecosystem/install-scripts
      - ./formal-verification:/ecosystem/formal-verification
    command: "/bin/bash"
